//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationPhotoLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdressSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdressSet()
        {
            this.PhotoSet = new HashSet<PhotoSet>();
        }
    
        public int Id { get; set; }
        public string Street { get; set; }
        public string PlaceNr { get; set; }
        public string City { get; set; }
        public string AssignedPerson { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public decimal GpsWidth { get; set; }
        public decimal GpsLength { get; set; }
        public bool East { get; set; }
        public bool North { get; set; }
        public string Building { get; set; }
        public int Owner_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoSet> PhotoSet { get; set; }
        public virtual OwnerSet OwnerSet { get; set; }
    }
}
