//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationPhotoLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoSet
    {
        public int Id { get; set; }
        public decimal GpsWidth { get; set; }
        public decimal GpsLength { get; set; }
        public bool East { get; set; }
        public bool North { get; set; }
        public string Filename { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime Datumimport { get; set; }
        public string IsMainseat { get; set; }
        public int Adress_Id { get; set; }
    
        public virtual AdressSet AdressSet { get; set; }
    }
}
